### ISSUE TITLE
How add fingerprints 

### ISSUE THREAD

**Issue by pasparakis** [akuehlewind/ESPHome-Fingerprint-Display-VideoDoorbell#1]
Hello,thank you for your project!
i have completed everything..but i don't know how to save a fingerprint
![IMG_8368](https://github.com/user-attachments/assets/3762c6b9-c3fb-49d1-9cdd-4ddeb8438fd1)
![IMG_8369](https://github.com/user-attachments/assets/b681305a-38ea-464e-96df-b2be1a133070)

**Comment by akuehlewind** [comment]
In HomeAssistant go to developer tools -> serices and look for a service called "ESPHome: fingerprint_display_enroll" (or similar". Set a finger_id (any number as id for the finger) and execute. Now place the finger multiple times on the sensor till the finger is scanned. The sensor gets back to normal mode after scan is complete.

![image](https://github.com/user-attachments/assets/0e194544-84b2-4bdd-a9b6-72abe3db9337)

**Comment by pasparakis** [comment]
Thank you for your answer!

I will look for it ..one more question: to open a door I only need to change the entity id in your configuration in this part?![image](https://github.com/user-attachments/assets/d23f99a3-c04e-4e7d-a9a7-1deb506350ac)

**Comment by akuehlewind** [comment]
This entity is only to show the garage door status on the display as an icon. To open and close using the fingerprint sensor simply add an automation to HA using the state front the fingerprint entity. So if state changes to „Authorized Finger“ then trigger whatever you want

![image](https://github.com/user-attachments/assets/cd253500-b821-4c77-8d05-2a49154c69ee)

**Comment by pasparakis** [comment]
Hello!

I've been working for the last few days and I think everything is working!!
I can't find the way to to show the notification..

i created helpers according to your description but nothing is displayed on the screen.

![image](https://github.com/user-attachments/assets/d3070389-74f0-4f65-8672-d7d96a0c6c41)


![image](https://github.com/user-attachments/assets/965db0b8-8a29-48d0-8eed-5340d0a84b75)

![image](https://github.com/user-attachments/assets/87255b46-9da4-4a23-834e-c0f822cfc2da)

**Comment by akuehlewind** [comment]
Did you set a value for the text in the helper for "input_text.doorbell_text". According to the code I'm using for the display in esphome it should change the page to show the notification page according to if the text is empty or not.

`- platform: homeassistant
    id: doorbell_text
    entity_id: input_text.doorbell_text
    internal: true
    on_value:
      then:
        - display.page.show: !lambda |-
            if (id(doorbell_text).state != "") {
              return notification_page;
            }
            else{
              return lockscreen_page;
            }
`

**Comment by pasparakis** [comment]
I understand..where I have marked, should I put the text that will be shown on the screen?
![image](https://github.com/user-attachments/assets/4880cec0-c4f5-49a3-a51b-8d32df4b4a5b)

**Comment by akuehlewind** [comment]
yes. You don't need quotation marks, just enter the text and put a comma as a line break. I'm not sure if the quotation marks are a problem. Last char has to be a comma otherwise the line is not shown for now. Feel tree to improve the parsing in esphome script :-D

**Comment by pasparakis** [comment]
i tried but no success..

I think everything is fine..I can't find the reason why it doesn't display the message![image](https://github.com/user-attachments/assets/34f6e843-3de0-41a8-a31a-a768902932cf)
![image](https://github.com/user-attachments/assets/a0af8b8f-5dd3-47e8-804b-b216de64e263)
![image](https://github.com/user-attachments/assets/ff8014a2-0671-43da-91e2-fe4d7f6d1a59)
![image](https://github.com/user-attachments/assets/c31df263-b156-4e22-86fd-966e300bcd7c)
![image](https://github.com/user-attachments/assets/1c53a986-f754-42da-a643-46cc52e265ea)

**Comment by pasparakis** [comment]
Final photo:
![image](https://github.com/user-attachments/assets/2e91d889-45f0-4936-9fe7-d5c4f83b5bbe)

Thank you for your project!

all that remains is to put the Greek language in the code..could you help me?
